const endPoints = {
  users: "users/",
  authors: "authors/",
  tags: "tags/",
  email: "email/",
  events: "events/",
  categories: "categories/",
  login: "login/",
  me: "me/",
  refresh: "token/refresh/",
  logout: "logout/",
  posts: "posts/",
  surveys: "surveys/",
  comment: "comments/",
  mediaFiles: "media-files/",
  surveyOptions: "survey-options/",
  vote: "survey-options/vote/",
  surveyOptionsById: "survey-options/by-survey/",
  postFiles: "media-files/by-post/",
  surveyPost: "surveys/by-post/",
  backup: "backup/",
  contentType: "content_type/",
  statistics: "posts/statistics/",
};

export default endPoints;
