import {
  faClose,
  faDatabase,
  faEnvelope,
  faEye,
  faFeather,
  faFilePdf,
  faHashtag,
  faImage,
  faMagnifyingGlass,
  faMusic,
  faNewspaper,
  faPenToSquare,
  faPlus,
  faShareFromSquare,
  faTags,
  faTrash,
  faUserPlus,
  faUsers,
  faVideo,
} from "@fortawesome/free-solid-svg-icons";

export const icons = {
  users: faUsers,
  addUser: faUserPlus,
  add: faPlus,
  delete: faTrash,
  share: faShareFromSquare,
  close: faClose,
  search: faMagnifyingGlass,
  update: faPenToSquare,
  tags: faHashtag,
  category: faTags,
  author: faFeather,
  view: faEye,
  email: faEnvelope,
  posts: faNewspaper,
  image: faImage,
  pdf: faFilePdf,
  video: faVideo,
  audio: faMusic,
  backup: faDatabase,
};
